# Generated by Django 2.2.2 on 2020-02-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190809_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tranche_horaire',
            field=models.CharField(choices=[('entre 10h et 12h', 'entre 10h et 12h'), ('entre 12h et 14h', 'entre 12h et 14h'), ('entre 14h et 16h', 'entre 14h et 16h'), ('entre 16h et 18h', 'entre 16h et 18h'), ('entre 18h et 20h', 'entre 18h et 20h')], default=None, max_length=200),
        ),
    ]
